name: CI

on:
  # pull_request:
  #   branches: ["*"]
  push:
    branches: ["*"]

# You can leverage Vercel Remote Caching with Turbo to speed up your builds
# @link https://turborepo.org/docs/core-concepts/remote-caching#remote-caching-on-vercel-builds
env:
  TURBO_TEAM: k6
  TURBO_TOKEN: orXUG7C0upy1PfeztANQZEBp

jobs:
  build:
    # env:
    #   DATABASE_URL: postgres://vsamaru:3WZsgHBC8tqE@ep-weathered-mouse-851080.eu-central-1.aws.neon.tech/ve
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
            node-version: 16
            cache: 'npm'
 
      - name: Install dependencies
        run: npm install
 
      - name: Build
        run: npm run build && npm run deploy --prod

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: './apps/web/dist'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy from GitHub Actions"
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
        env:
          NETLIFY_AUTH_TOKEN: Rh2EJPNVrNotTRbUlOjREJMJTAEtjHJeNp2aXM05IW8
          NETLIFY_SITE_ID: 19ee4990-51ce-42be-9611-cb21cb18accd
        timeout-minutes: 1